// <auto-generated />
using System;
using CafeteriaElPuntoRojo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace POSBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CafeteriaElPuntoRojo.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Cafés"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Pasteles"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Bebidas Frías"
                        });
                });

            modelBuilder.Entity("CafeteriaElPuntoRojo.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("CafeteriaElPuntoRojo.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Nombre = "Café Americano",
                            Precio = 25m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Nombre = "Café Latte",
                            Precio = 35m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Nombre = "Café Capuchino",
                            Precio = 38m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            Nombre = "Pastel de Chocolate",
                            Precio = 45m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Nombre = "Pastel de Vainilla",
                            Precio = 40m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Nombre = "Frappé de Vainilla",
                            Precio = 55m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 3,
                            Nombre = "Frappé de Fresa",
                            Precio = 55m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Nombre = "Brownie",
                            Precio = 30m,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("CafeteriaElPuntoRojo.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("CafeteriaElPuntoRojo.Models.DetalleVenta", b =>
                {
                    b.HasOne("CafeteriaElPuntoRojo.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeteriaElPuntoRojo.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("CafeteriaElPuntoRojo.Models.Producto", b =>
                {
                    b.HasOne("CafeteriaElPuntoRojo.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CafeteriaElPuntoRojo.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CafeteriaElPuntoRojo.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
